version: '3.9'
services:
  appoxy:
    container_name: appoxy-droidnet-proxy
    hostname: appoxy-droidnet-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./droidnet.nginx:/etc/nginx/conf.d/default.conf
    networks:
        - appoxy-droidnet
        - appoxy-corenet
networks:
    appoxy-droidnet:
        external: true
    appoxy-corenet:
        external: true
